/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_3_3_Orange_aliases.h"
#include "Pin_3_3_Orange.h"
#include "Pin_3_4_Blue_aliases.h"
#include "Pin_3_4_Blue.h"
#include "LCD_Char_1.h"
#include "Pin_0_5_Pink_aliases.h"
#include "Pin_0_5_Pink.h"
#include "Pin_0_3_Yellow_aliases.h"
#include "Pin_0_3_Yellow.h"
#include "Pin_0_0_Slider_aliases.h"
#include "Pin_0_0_Slider.h"
#include "Pin_0_1_y_aliases.h"
#include "Pin_0_1_y.h"
#include "ADC_SAR_2.h"
#include "ADC_SAR_1.h"
#include "Pin_3_0_MotorControlA_aliases.h"
#include "Pin_3_0_MotorControlA.h"
#include "Pin_3_1_MotorControlB_aliases.h"
#include "Pin_3_1_MotorControlB.h"
#include "Pin_12_4_LDRTop_aliases.h"
#include "Pin_12_4_LDRTop.h"
#include "Pin_12_5_LDRBottom_aliases.h"
#include "Pin_12_5_LDRBottom.h"
#include "isr_top.h"
#include "isr_bottom.h"
#include "Timer_1.h"
#include "isr_up.h"
#include "Timer_2.h"
#include "isr_down.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "ADC_SAR_2_Bypass_aliases.h"
#include "ADC_SAR_2_Bypass.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

